services:
  openldap:
    image: bitnami/openldap:latest
    container_name: openldap-server
    environment:
      - LDAP_ROOT=dc=contenedores
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=123
      - LDAP_TLS_ENABLED=no
      - LDAP_CUSTOM_LDIF_DIR=/ldifs
    ports:
      - "1389:1389"

    volumes:
      - ./openldap_data:/bitnami/openldap
      - ./openldap/ldif/bootstrap:/ldifs:ro

